# Run checks and test suite. Intended to be run ahead of building / containerising the app.
#
# Usage:
# ```
# jobs:
#   checks:
#     uses: ./.github/workflows/_checks.yaml
# ```
name: Pre-build checks

on:
  workflow_call:

jobs:
  pre_commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/pre-commit

  generate-nox-sessions:
    runs-on: ubuntu-24.04
    outputs:
      session: ${{ steps.set-matrix.outputs.session }}
    steps:
    - uses: actions/checkout@v5
    - uses: wntrblm/nox@2025.05.01
    - id: set-matrix
      shell: bash
      run: |
        # Extract all nox session names (both selected and skipped) into a JSON array.
        # Session lines start with '*' or '-'.
        sessions_json="$(
        nox --list \
            | grep -E '^[*-] ' \
            | cut -d' ' -f2 \
            | jq -R -s -c 'split("\n")[:-1]'
        )"
        echo "session=$sessions_json" >> "$GITHUB_OUTPUT"

  test:
    needs:
      - pre_commit
      - generate-nox-sessions
    strategy:
      fail-fast: false
      matrix:
        session: ${{ fromJson(needs.generate-nox-sessions.outputs.session) }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"
          enable-cache: true
      - uses: wntrblm/nox@2025.05.01
      - run: nox --session "${{ matrix.session }}"
