# Continuous Integration pipeline
# Runs when a Pull Request is merged into the 'main' branch.
name: CI

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  pre_commit:
    # this job is redundant if pipeline was triggered by merge of a 'Release Please' PR
    if: ${{ github.event.pull_request.merged && github.head_ref != 'release-please--branches--main' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pre-commit

  generate-nox-sessions:
    # this & 'test' job redundant if pipeline triggered by merging a 'Release Please' PR
    if: github.head_ref != 'release-please--branches--main'
    needs:
      - pre_commit
    runs-on: ubuntu-24.04
    outputs:
      session: ${{ steps.set-matrix.outputs.session }}
    steps:
    - uses: actions/checkout@v4
    - uses: wntrblm/nox@main
    - id: set-matrix
      shell: bash
      run: echo session=$(nox --json -l | jq -c '[.[].session]') | tee --append $GITHUB_OUTPUT

  test:
    needs:
      - generate-nox-sessions
    strategy:
      fail-fast: false
      matrix:
        session: ${{ fromJson(needs.generate-nox-sessions.outputs.session) }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.17"
      - uses: wntrblm/nox@2025.02.09
      - run: nox --session "${{ matrix.session }}"
