# Continuous Integration pipeline
# Runs when a Pull Request is merged into the 'main' branch.
name: CI

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  checks:
    # this job is redundant if pipeline was triggered by merge of a 'Release Please' PR
    if: ${{ github.event.pull_request.merged && github.head_ref != 'release-please--branches--main' }}
    uses: ./.github/workflows/_pre-build-checks.yaml
