# Continuous Integration pipeline
# Runs when a Pull Request is merged into the 'main' branch.
name: CI

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  pre_commit:
    # this job is redundant if pipeline was triggered by merge of a 'Release Please' PR
    if: ${{ github.event.pull_request.merged && github.head_ref != 'release-please--branches--main' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pre-commit

  test:
    # this job is redundant if pipeline was triggered by merge of a 'Release Please' PR
    if: github.head_ref != 'release-please--branches--main'
    needs:
      - pre_commit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
