# Pull Request pipeline
# Runs when a commit on a feature branch is pushed up to GitHub.
name: PR

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  pre_commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pre-commit

  generate-nox-py-versions:
    needs:
      - pre_commit
    runs-on: ubuntu-24.04
    outputs:
      session: ${{ steps.set-matrix.outputs.session }}
    steps:
    - uses: actions/checkout@v4
    - uses: wntrblm/nox@main
    - id: set-matrix
      shell: bash
      run: echo session=$(nox --json -l | jq -c '[.[].session]') | tee --append $GITHUB_OUTPUT

  test:
    needs:
      - generate-nox-py-versions
    strategy:
      fail-fast: false
      matrix:
        session: ${{ fromJson(needs.generate-nox-py-versions.outputs.session) }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.17"
      - uses: wntrblm/nox@2025.02.09
      - run: nox --session "${{ matrix.session }}"
