# Re-usable GitHub Action that runs all pre-commit hooks.
#
# Usage:
#   ```
#   steps:
#     - uses: ./.github/actions/prek
#   ```

name: 'prek'
description: 'Run all pre-commit hooks against the codebase'

runs:
  using: 'composite'
  steps:
    # global shared state: modifies `env` inside this action AND outside in the caller.
    - run: |
        # Skip hook since it causes issues when merging PRs, and already enforced by GitHub config.
        echo "SKIP=no-commit-to-branch" >> $GITHUB_ENV
      shell: bash
    - uses: actions/setup-python@v6
    - uses: j178/prek-action@v1
