# pycliche Pull Request pipeline
# Runs when a commit on a feature branch is pushed up to GitHub.
name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/_checks.yaml
